# Generated by Django 3.0.8 on 2022-10-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('phone_customer', models.CharField(max_length=50)),
                ('address_customer', models.CharField(max_length=100)),
            ],
        ),
    ]
