# Generated by Django 3.0.8 on 2022-10-14 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221014_1010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table=None,
        ),
    ]
