# Generated by Django 3.0.8 on 2022-10-15 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False},
        ),
    ]
