# Generated by Django 3.0.8 on 2022-10-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20221015_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customers')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
            ],
            options={
                'unique_together': {('id_customer', 'id_product')},
            },
        ),
    ]
