# Generated by Django 3.0.8 on 2022-10-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
