# Generated by Django 3.0.8 on 2022-10-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20221018_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_id_customer', to='home.customers'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_id_product', to='home.products'),
        ),
    ]
