# Generated by Django 3.0.8 on 2022-10-20 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_order_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order_product',
            unique_together={('id_order', 'id_product')},
        ),
    ]
