# Generated by Django 3.0.8 on 2022-10-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20221020_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sum_price',
            field=models.FloatField(),
        ),
    ]
