# Generated by Django 3.0.8 on 2022-10-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20221020_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customers')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
            ],
            options={
                'db_table': 'rating_product',
                'unique_together': {('id_product', 'id_customer')},
            },
        ),
    ]
