# Generated by Django 3.0.8 on 2022-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_product',
            name='cmt',
            field=models.TextField(default=''),
        ),
    ]
